name: "Texecom Premier"
description: "Texecom Premier Home Assistant Add-on"
version: "0.1.5"
slug: "texecom_premier"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
